name: BedWars
version: '${project.version}'
main: org.ast.bedwarspro.BedWars
commands:
  bp:
    description: BedWars game command
    usage: /bp <set|open>
    permission: true  # 允许所有人执行此命令
    aliases: [bedwars]
