name: BedWarsPro
version: '${project.version}'
main: org.ast.bedwarspro.BedWarsPro

commands:
  bp:
    description: 起床战争辅助功能
    usage: /bp <set|open|menu>
    permission: bedwarspro.use.bp
    aliases: [bedwars]

  bps:
    description: 生存服务器
    usage: /bps <enchant|randomTp|tp|menu>
    permission: bedwarspro.use.bps
    aliases: [bps]

  lobby:
    description: Hub command
    usage: /lobby
    permission: bedwarspro.use.lobby
